### ISSUE TITLE
WebSocketEndpoint的属性只有String类型可以使用${...}占位符

### ISSUE THREAD

**Issue by lhtzbj12** [twelvet-s/netty-websocket-spring-boot-starter#6]
如题，需要将int、boolean等以及默认值改成String

**Comment by twelvet-s** [comment]
你的问题已知晓，不久将修正

**Comment by lhtzbj12** [comment]
谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月29日 20:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [twelvet-s/netty-websocket-spring-boot-starter] WebSocketEndpoint的属性只有String类型可以使用${...}占位符 (Issue #6) |

你的问题已知晓，不久将修正

**Comment by twelvet-s** [comment]
已发布1.0.6修复版本

**Comment by lhtzbj12** [comment]
收到，很给力



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月31日 17:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [twelvet-s/netty-websocket-spring-boot-starter] WebSocketEndpoint的属性只有String类型可以使用${...}占位符 (Issue #6) |

已发布1.0.6修复版本
